### ISSUE TITLE
number of teeth on wheels

### ISSUE THREAD

**Issue by metaphorz** [nikital/clock#3]
Is the number of teeth on each wheel correct? I ask because I counted the teeth on
two wheels that connect the main minute arbor to the hour arbor (requiring a 12:1 ratio).
I may have miscounted the teeth but could not see a 12:1.

**Comment by nikital** [comment]
You're correct, thanks for bringing it up!
The ratios should be 36:12 followed by 40:10, so that's 12:1.

**Comment by metaphorz** [comment]
Nikita

I forgot -- did your clock also have a second hand? Does it use physics or animation to turn the gears?

Paul 

Paul Fishwick, PhD,
Chair, ACM SIGSIM
Distinguished University Chair of Arts & Technology and Professor of Computer Science
The University of Texas at Dallas
Arts & Technology
800 West Campbell Road, AT10
Richardson, TX 75080-3021
Lab: http://creative-automata.com
SIGSIM: http://modelingforeveryone.com
Twitter: @PaulFishwick

**Comment by nikital** [comment]
The clock did not have a second hand, only hours and minutes.

The simulation is not based on physics, it's just animation. [Here](https://github.com/nikital/clock/blob/dfef567b508d5a5ac9195e64aac74b07bb6d6476/src/mechanics.ts#L31) are the ratios for the gears, and [here](https://github.com/nikital/clock/blob/dfef567b508d5a5ac9195e64aac74b07bb6d6476/src/mechanics.ts#L138) is the code that uses the ratios to drive the animation.

**Comment by metaphorz** [comment]
Thanks for your excellent work to date. I'd like to do some physical gear based work but unsure whether webgl has anything, or whether there is another JavaScript 3D solution

P

Paul Fishwick, PhD,
Chair, ACM SIGSIM
Distinguished University Chair of Arts & Technology and Professor of Computer Science
The University of Texas at Dallas
Arts & Technology
800 West Campbell Road, AT10
Richardson, TX 75080-3021
Lab: http://creative-automata.com
SIGSIM: http://modelingforeveryone.com
Twitter: @PaulFishwick

**Comment by nikital** [comment]
WebGL is just a rendering technology, it has nothing to do with actual gear simulation.
Also, this demo doesn't use WebGL directly, but relies on three.js to do the rendering.
Good luck!
